# ==============================================================================
# RNA-seq Differential Expression Analysis Pipeline (From RAW to GSEA)
# Project: PRJNA1175381 - Zebrafish (Danio rerio) Exposure Analysis
# Author: Abdelrahman Elsayed Mohamed
# ==============================================================================


# Required packages 
# Install CRAN packages
install.packages("reader")
install.packages("readr")
install.packages("readxl")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("tidyverse")
install.packages("datapasta")
install.packages("matrixStats")
install.packages("rhdf5")
install.packages("gt")
install.packages("DT")
install.packages("plotly")
install.packages("cowplot")
install.packages("openxlsx")

# Install Bioconductor packages
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("vsn")
BiocManager::install("AnnotationDbi")
BiocManager::install("tximport")
BiocManager::install("ensembldb")
BiocManager::install("org.Dr.eg.db")
BiocManager::install("edgeR")
BiocManager::install("biomaRt")
BiocManager::install("apeglm")
BiocManager::install("clusterProfiler")
BiocManager::install("EnhancedVolcano")
BiocManager::install("org.Hs.eg.db")
BiocManager::install("clusterProfiler")

library(reader)
library(readr)
library(readxl)
library(AnnotationDbi)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(tximport)
library(ensembldb)
library(datapasta)
library(matrixStats)
library(rhdf5)
library(gt)
library(biomaRt)
library(DT)
library(plotly)
library(cowplot)
library(edgeR)
library(org.Dr.eg.db)
library(pheatmap)
library(DESeq2)
library(pheatmap)
library(readxl)
library(EnhancedVolcano)
library(clusterProfiler)
library(org.Hs.eg.db)
library(clusterProfiler)
library(apeglm)
library(openxlsx)

# set path for data files and abundance files
setwd("G:/RNA_seq/PRJNA1175381")

# 1. Load and Prepare Metadata
# --------
# Load sample information from Excel file
samples <- read.xlsx("G:/RNA_seq/PRJNA1175381/PRJNA1175381_metadata.xlsx")
samples <- as.data.frame(samples)

# Set sample names as row names to align with count data
rownames(samples) <- samples$sample

# Convert the experimental variable to a factor
samples$condition <- factor(samples$condition)


# 2. Define Paths to Kallisto Output Files
# ----------------
# Construct file paths for abundance.h5 files generated by Kallisto
files <- file.path("kallisto_out", samples$sample, "abundance.tsv")
names(files) <- samples$sample

# Verify that all specified files exist before proceeding
if(!all(file.exists(files))) {
  stop("Error: One or more abundance.h5 files were not found at the specified paths.")
}
# 3. Create Transcript-to-Gene Mapping (WITH GENE SYMBOLS)
# ------------------------------------------------------------------------------
# Connect to Ensembl BioMart for Danio rerio (Zebrafish)
mart <- useMart("ensembl", dataset = "drerio_gene_ensembl")

# Retrieve transcript IDs, Ensembl IDs, and External Gene Names (Symbols)
tx2gene_raw <- getBM(attributes = c("ensembl_transcript_id", "ensembl_gene_id", "external_gene_name"), 
                     mart = mart)

# Smart Mapping: Use Symbol if available, otherwise fallback to Ensembl ID
# This prevents empty labels in your plots
tx2gene_raw$final_gene <- ifelse(tx2gene_raw$external_gene_name == "", 
                                 tx2gene_raw$ensembl_gene_id, 
                                 tx2gene_raw$external_gene_name)

# Create the final 2-column mapping required by tximport
tx2gene <- tx2gene_raw[, c("ensembl_transcript_id", "final_gene")]

#  Import Quantification Data with tximport
# ------------------------------------------------------------------------------
# Now 'txi' will use Gene Symbols as row names automatically
txi <- tximport(files, 
                type = "kallisto", 
                tx2gene = tx2gene, 
                ignoreTxVersion = TRUE)

#  Extract and Calculate Statistics
# ------------------------------------------------------------------------------
library(matrixStats) # Ensure matrixStats is loaded for rowSds/rowMedians

tpm_stats <- as.data.frame(txi$abundance) %>%
  setNames(samples$sample) %>%
  mutate(SD  = rowSds(as.matrix(.)), 
         AVG = rowMeans(.), 
         MED = rowMedians(as.matrix(.)))

  # Update row names for tpm_stats to match gene symbols
rownames(tpm_stats) <- rownames(txi$abundance)

#  Export Gene Counts to Excel (Now with readable Gene Names)
library(openxlsx)
write.xlsx(as.data.frame(txi$counts), "Gene_Counts_Matrix_Symbols.xlsx", rowNames = TRUE)

#  Visualization of TPM Distribution 
# ------------------------------------------------------------------------------
ggplot(tpm_stats, aes(x = SD, y = MED)) +
  geom_point(alpha = 0.3, color = "midnightblue") + 
  labs(title = "TPM Distribution: Variability vs. Expression",
       x = "Standard Deviation (SD)", y = "Median Expression (MED)") +
  theme_minimal()

# 5. Construct DESeq2 Object
# ------------------------------------------------------------------------------
# We ensure condition is a factor and 'control' is the reference level
samples$condition <- factor(samples$condition)
#Set 'control' as the reference level for statistical comparison
samples$condition <- relevel(samples$condition, ref = "control")

dds <- DESeqDataSetFromTximport(txi, 
                                colData = samples, 
                                design = ~ condition)

# 6. Pre-processing & Filtering
# ------------------------------------------------------------------------------
# Basic pre-filtering: remove genes with low total counts (at least 10 reads)
# This improves the speed and power of statistical tests
keep <- rowSums(counts(dds)) >= 10
dds <- dds[keep, ]

# Verify the object structure
print(dds)


# 7. Run DESeq2 Pipeline
# ------------------------------------------------------------------------------
dds <- DESeq(dds)


# 8. Data Transformation (For Quality Control Plots)
# ------------------------------------------------------------------------------
# Variance Stabilizing Transformation (VST) minimizes the variance-mean dependence
# blind = FALSE because we want to account for our experimental design
vsd <- vst(dds, blind = FALSE)


# 9. Extract and Shrink Results (LFC Shrinkage)
# ------------------------------------------------------------------------------
# First, extract raw results to set alpha threshold
res_raw <- results(dds, contrast = c("condition", "PS_NPs", "control"), alpha = 0.05)

# Then, apply apeglm shrinkage to Log2 Fold Changes for better accuracy
# res_names[2] ensures we target the PS-NPs vs Control comparison
res_names <- resultsNames(dds)
res_shrunk <- lfcShrink(dds, coef = res_names[2], type = "apeglm")


# 10. Results Processing and Filtering
# ------------------------------------------------------------------------------
# Convert results to a data frame and remove NA values
res_df <- as.data.frame(res_shrunk)
res_clean <- res_df[!is.na(res_df$padj), ]

# Add a significance column based on Padj < 0.05 and |LFC| > 0.5
res_clean$significance <- "Not Significant"
res_clean$significance[res_clean$padj < 0.05 & abs(res_clean$log2FoldChange) > 0.5] <- "Significant"


# 11. Categorize DEGs (Up and Downregulated)
# ------------------------------------------------------------------------------
upregulated <- res_clean[res_clean$log2FoldChange > 0.5 & res_clean$padj < 0.05, ]
downregulated <- res_clean[res_clean$log2FoldChange < -0.5 & res_clean$padj < 0.05, ]


# 12.Visualizations
# ------------------------------------------------------------------------------

# A. PCA Plot
plotPCA(vsd, intgroup = "condition") +
  theme_minimal() +
  scale_color_brewer(palette = "Set1") +
  ggtitle("Principal Component Analysis (PCA)") +
  geom_text(aes(label = name), vjust = 1.5, size = 3)

# B. MA-Plot
plotMA(res_shrunk, main = "MA-Plot (LFC Shrunk): PS-NPs vs Control", ylim = c(-4, 4))

# C.Volcano Plot (Using EnhancedVolcano)
# ------------------------------------------------------------------------------

library(EnhancedVolcano)

# Open a PNG device to save the plot
png("Volcano_Plot_Final.png", width = 3000, height = 2400, res = 300)

EnhancedVolcano(res_shrunk,
                lab = rownames(res_shrunk),
                x = 'log2FoldChange',
                y = 'padj',
                selectLab = head(rownames(res_clean[order(res_clean$padj), ]), 10),
                pCutoff = 0.05,
                FCcutoff = 0.5,
                pointSize = 2.0,
                labSize = 4.0,
                title = 'Differential Gene Expression: PS-NPs vs. Control',
                subtitle = bquote(italic("D. rerio") ~ "larvae exposure | Shrunk LFC (apeglm)"),
                legendPosition = 'right',
                drawConnectors = TRUE,
                widthConnectors = 0.5)

# Close the device
dev.off()


# D. Heatmap (Using Z-score Scaling)
# ------------------------------------------------------------------------------
library(pheatmap)

# 1. Select the top 30 genes with the smallest adjusted p-values
top30_genes <- head(rownames(res_clean[order(res_clean$padj), ]), 30)

# 2. Extract VST-transformed counts for these genes
mat <- assay(vsd)[top30_genes, ]

# 3. Apply Z-score Normalization (Scaling by row)
# This centers each gene's expression to its mean and scales by its standard deviation
# Formula: z = (x - mean) / sd
mat_scaled <- t(scale(t(mat)))

# 4. Generate the Heatmap
pheatmap(mat_scaled, 
         annotation_col = as.data.frame(colData(dds)[, "condition", drop = FALSE]),
         show_rownames = TRUE, 
         show_colnames = TRUE,
         cluster_cols = TRUE,    # Cluster samples based on similarity
         cluster_rows = TRUE,    # Cluster genes based on expression patterns
         main = "Top 30 DEGs Heatmap",
         color = colorRampPalette(c("blue", "white", "red"))(100),
         border_color = NA)



# 13. Data Export
# ------------------------------------------------------------------------------
# Full results (shrunk) ordered by significance
write.csv(res_clean[order(res_clean$padj), ], "DESeq2_full_results_shrunk.csv")

# Significant Upregulated and Downregulated files
write.csv(upregulated[order(upregulated$padj), ], "DEGs_Upregulated.csv")
write.csv(downregulated[order(downregulated$padj), ], "DEGs_Downregulated.csv")


# 14. Final Statistical Summary
# ------------------------------------------------------------------------------
cat("Total genes tested:      ", nrow(res_clean), "\n")
cat("Significant DEGs:        ", nrow(upregulated) + nrow(downregulated), "\n")
cat("Upregulated (PS-NPs):    ", nrow(upregulated), "\n")
cat("Downregulated (PS-NPs):  ", nrow(downregulated), "\n")


# 15. Top 10 genes by statistical significance  (Upregulated & Downregulated )
# ------------------------------------------------------------------------------

library(dplyr)
install.packages("writexl")
library(writexl)

# 1. Identify Top 10 genes by statistical significance (lowest padj)
# This includes both Up and Downregulated genes
top10_statistically <- res_clean %>%
  as.data.frame() %>%
  mutate(Gene_Symbol = rownames(.)) %>%      # Convert row names to a real column
  relocate(Gene_Symbol, .before = baseMean)  # Move Gene_Symbol to the first position
  arrange(padj) %>% 
  head(10)
print(top10_statistically)

# 2. Identify Top 10 most strongly Upregulated genes
# Filters for significance (padj < 0.05) then sorts by highest Log2 Fold Change
top10_up <- res_clean %>%
  as.data.frame() %>%
  mutate(Gene_Symbol = rownames(.)) %>%      # Convert row names to a real column
  relocate(Gene_Symbol, .before = baseMean)  # Move Gene_Symbol to the first position
  filter(padj < 0.05) %>%
  arrange(desc(log2FoldChange)) %>%
  head(10)

# 3. Identify Top 10 most strongly Downregulated genes
# Filters for significance (padj < 0.05) then sorts by lowest (most negative) Log2 Fold Change
top10_down <- res_clean %>%
  as.data.frame() %>%
  mutate(Gene_Symbol = rownames(.)) %>%      # Convert row names to a real column
  relocate(Gene_Symbol, .before = baseMean)  # Move Gene_Symbol to the first position
  filter(padj < 0.05) %>%
  arrange(log2FoldChange) %>%
  head(10)

# 4. Export the results into a single Excel file with multiple sheets
write_xlsx(list("Statistical_Top10" = top10_statistically, 
                "Upregulated_Top10" = top10_up, 
                "Downregulated_Top10" = top10_down), 
           path = "Top_10_Genes_Analysis.xlsx")


# 16. Gene Set Enrichment Analysis (GSEA)
# ------------------------------------------------------------------------------

# 1. Create a ranked list using a combined metric: -log10(pvalue) * sign(log2FoldChange)
res_for_gsea <- res_clean %>%
  mutate(rank_metric = -log10(pvalue) * sign(log2FoldChange)) %>%
  arrange(desc(rank_metric))

# Extract the ranked vector
gene_list <- res_for_gsea$rank_metric
names(gene_list) <- rownames(res_for_gsea)

# Quick check of the top and bottom of your list
head(gene_list) # Strongest Upregulated
tail(gene_list) # Strongest Downregulated


# 2. Convert Gene Symbols to Entrez IDs (Required for KEGG)
ids <- bitr(names(gene_list), 
            fromType = "SYMBOL", 
            toType   = "ENTREZID", 
            OrgDb    = org.Dr.eg.db)

# Merge IDs with our ranked list
# Remove duplicates if any to keep the ranking clean
gene_list_entrez <- gene_list[names(gene_list) %in% ids$SYMBOL]
names(gene_list_entrez) <- ids$ENTREZID[match(names(gene_list_entrez), ids$SYMBOL)]
gene_list_entrez <- sort(gene_list_entrez, decreasing = TRUE)

# 3. Run GSEA for Biological Processes (BP)
gsea_go <- gseGO(geneList     = gene_list, # We can use Symbols directly for GO
                 OrgDb        = org.Dr.eg.db,
                 ont          = "BP", 
                 keyType      = "SYMBOL",
                 minGSSize    = 10,
                 maxGSSize    = 500,
                 pvalueCutoff = 0.05,
                 verbose      = FALSE,
                 seed         = TRUE)

# Export GSEA results to Excel
write.xlsx(as.data.frame(gsea_go), "GSEA_Biological_Processes_Results.xlsx")


library(enrichplot)

# A. Dotplot
# --------------------------------------------------
pdf("GSEA_Dotplot.pdf", width = 10, height = 8)
dotplot(gsea_go, showCategory = 15, split = ".sign") + 
  facet_grid(.~.sign) +
  scale_y_discrete(labels = function(x) str_wrap(x, width = 40)) +
  ggtitle("Enriched Biological Processes: PS-NPs vs. Control")
dev.off()

# B. Ridge Plot
# --------------------------------------------------
pdf("GSEA_RidgePlot.pdf", width = 15, height = 15)
ridgeplot(gsea_go) + 
  labs(x = "Enrichment Distribution (Log2FC)") +
  ggtitle("Expression Density per Pathway")
dev.off()


# 1. Export Top 10 Activated Pathways (Highest Positive NES)
activated_pathways <- as.data.frame(gsea_go) %>%
  filter(NES > 0) %>%
  arrange(desc(NES)) %>%
  head(10)

# 2. Export Top 10 Suppressed Pathways (Most Negative NES)
suppressed_pathways <- as.data.frame(gsea_go) %>%
  filter(NES < 0) %>%
  arrange(NES) %>%
  head(10)

# Save both in one Excel file with two sheets
library(openxlsx)
write.xlsx(list("Activated_Top10" = activated_pathways, 
                "Suppressed_Top10" = suppressed_pathways), 
           "GSEA_Top_Activated_vs_Suppressed.xlsx")


# Top Pathway Curve
pdf("GSEA_Top_Pathway_Curve.pdf", width = 8, height = 6)
gseaplot2(gsea_go, geneSetID = 1, title = gsea_go$Description[1], pvalue_table = TRUE)
dev.off()

# Cnetplot
pdf("GSEA_Network_Cnetplot.pdf", width = 12, height = 10)
# Convert to symbols for readable labels
edox <- setReadable(gsea_go, 'org.Dr.eg.db', 'SYMBOL')
cnetplot(edox, foldChange = gene_list, showCategory = 5, circular = TRUE, colorEdge = TRUE)
dev.off()

# Sample Distance Heatmap 
library(RColorBrewer)
sampleDists <- dist(t(assay(vsd)))
sampleDistMatrix <- as.matrix(sampleDists)
pdf("Sample_Distance_Heatmap.pdf")
pheatmap(sampleDistMatrix,
         clustering_distance_rows = sampleDists,
         clustering_distance_cols = sampleDists,
         col = colorRampPalette(rev(brewer.pal(9, "Blues")))(255))
dev.off()




